
PACKAGES = 
PACKAGES += appendixnumberbeamer.sty
PACKAGES += atlasphysics.sty
PACKAGES += beamerthemeCEA.sty
PACKAGES += beamerinnerthemecea.sty
PACKAGES += beamerouterthemecea.sty
PACKAGES += beamercolorthemecea.sty

main : 
	pdflatex master.tex
	pdflatex master.tex

clean :
	rm -f *.pdf 
	rm -f *~ 
	rm -f *.aux 
	rm -f *.log 
	rm -f *.nav 
	rm -f *.out 
	rm -f *.snm 
	rm -f *.toc
